baseurl: https://datamares.netlify.app/
copyright: Copyright © 2021, Alberson Miranda; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: 'datamares-1'
DefaultContentLanguage: pt
taxonomies:
  category: categories
  series: series
  tag: tags
