---
title: "Why Are Economists Always Wrong?"
subtitle: "An Epistemological Critique of the Maximizing Equilibrium Paradigm"
date: "2025-06-15"
categories: [economics]
bibliography: bib.bib
---

```{r options, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  out.width = "100%",
  warnings = FALSE,
  message = FALSE
)
```

In this post, I offer my reading of the first chapter of @feijo concerning what they called the maximizing equilibrium paradigm, henceforth referred to simply as the paradigm, in economic science.

# ECONOMICS AS AN EXACT SCIENCE

Still in their introduction, the authors argue about the position of economic science as an exact or human science:

>The first question that arises in the mind of the layman is whether economics is an exact science or a science in the field of the so-called humanities (human sciences). If we had to choose between one framework or another, we would say that economics belongs to the field of human sciences. However, it occupies a special position among the human sciences: a part of the scientific contributions of academic economists uses the method of exact sciences. Thus, it can be safely stated that there is an exact field within the scope of investigations made by economists. Not all studies offered by economists, however, appear as an effort in exact science. But an important part of them, indeed, the most expressive, employs the rigorous mathematical methods typical of the exact natural sciences that have physics as their central model.

These exact methods would have social norms as their object, reinforced by penal laws, which "encompass all types of regular and standardized behavior, equal for all individuals within a group." However, the authors themselves recognize the limited scope of economic science in the study of these social norms:

>For the economist, a few types of institutions, seen as stylized types, are sufficient, such as private property (which induces agents to respect property rights and contracts) and the optimizing agent (who maximizes utility or profit), or else communism (which coerces them to accept collective property) and the cooperating agent. A good part of the theoretical work of the economist refers to a few types of social institutions. For the paradigm of theoretical economics, the optimizing agent is of interest.

I question, firstly, whether there is coherence in trying to specify an exact field within a human science as the authors did. I do not mean by this that there are no laws in the realm of humanities—at least in the horizon of human experience in which we find ourselves—they not only exist but are studied by philosophers and represented in art^[Impossible to forget Macbeth's classic monologue: "And all our yesterdays have lighted fools The way to dusty death."] throughout the ages. Of the greatest of them, Seneca already treated in his letters to his father-in-law Paulinus:

>Most mortals, Paulinus, complain about the malice of Nature, because they are born with the prospect of a short existence and because the years given to them pass quickly and swiftly. So that, with the exception of a few, for the others, it is precisely in the splendor of life that it abandon them. [@seneca]

The individual's time is restricted to their always insufficient years; their place in the universe, confined to a single rock amidst the infinitude of the cosmos; bound to the ground by gravity; captive to the surface by the air itself; hostage to the need to consume. However, this consumption I mention does not refer to the idea of an exchange economy that some theorists posit as a natural and spontaneous order independent of social space, historicity, and the specificities of each society. I refer solely to the food that every animal needs to survive. This, indeed, is the consumption that is natural law. The adoption of maximizing behavior as a natural law represents one of several generalizations and extrapolations of this nature that are at the center of the critique of the paradigm, not mathematization itself.

When the authors state that the object of exact methods in economics is "all types of regular and standardized behavior, equal for all individuals within a group," they fail to see that there are very few of these regular and standardized behaviors. The regular behavior is: *man seeks food to survive*. However, *man knows the equilibrium price of food and will demand more of it if it is below this price* is not a natural law. If the mechanism of convergence to macroeconomic equilibrium is entirely anchored in the microfoundation of standardized rational behavior, the macroeconomics of the paradigm already becomes fragile, and any development and conclusion obtained from it, no matter how complex and mathematically advanced, will be biased.

It must be emphasized that the paradigm is not alone in these extrapolations. For example, Keynes standardizes human behavior with the *animal spirit*; Hayek assumes the invariability of the human spirit and the universality, in space and time, of the laws governing the economy in any society. @feijo follow the same path by defending the existence of an objective reality that is separate from the subject investigating it:

>There is something beyond a purely mental exercise involved in the work of the social scientist, for an objective reality thrives that must be rationally studied. Just as in the natural sciences, in the field of social investigation, one must also separate the knowledge formulated about facts, on the one hand, from external and objective reality itself, on other. With this, the traditional separation between the ideas elaborated about reality and this reality itself also extends to the domain of social science. The separation, usual in the physical sciences, between subject and object, partially violated only in quantum mechanics, also applies to the field of social studies.

The existence of a single objective reality is a presupposition of the positivist approach and an instrument of the method of exact sciences. In them, the researcher adopts a position of neutrality—they are a mere passive observer. Such reality does not exist in social science. The latter admits that reality can be seen from various perspectives, and the social researcher knows that their observation and conclusions are value-laden. For example, to assume the neutrality of Hayek's thought, who wrote *The Road to Serfdom* in 1944 under the influence of Nazi-fascist totalitarianism on one side, and the Soviets on the other; or that of Marx, who wrote *Das Kapital* in the era of panoptic factory-prisons, is concerning.

The guise of exact science undoubtedly provides a creative and elegant disguise for economic science. However, to the extent that this view requires the adoption of unsustainable hypotheses, it is not surprising that, after centuries of development of economic theory, crises still take economists by surprise.

It was so in 2008. The year after the crash, Paul Krugman wrote in his New York Times article:

>As I see it, the economics profession went astray because economists, as a group, mistook beauty, clad in impressive-looking mathematics, for truth. [...] the central cause of the profession’s failure was the desire for an all-encompassing, intellectually elegant approach that also gave economists a chance to show off their mathematical prowess. Unfortunately, this romanticized and sanitized vision of the economy led most economists to ignore all the things that can go wrong. They turned a blind eye to the limitations of human rationality that often lead to bubbles and busts; to the problems of institutions that run amok; to the imperfections of markets — especially financial markets — that can cause the economy’s operating system to undergo sudden, unpredictable crashes; and to the dangers created when regulators don’t believe in regulation. [@krugman]

This illusion is so ingrained in the paradigm that economists, both in academia and in the market, thought they had all the solutions^[``in a 2008 paper titled ´The State of Macro' (that is, macroeconomics, the study of big-picture issues like recessions), Olivier Blanchard of M.I.T., now the chief economist at the International Monetary Fund, declared that ´the state of macro is good'. The battles of yesteryear, he said, were over, and there had been a ´broad convergence of vision'. And in the real world, economists believed they had things under control: the ´central problem of depression-prevention has been solved', declared Robert Lucas of the University of Chicago in his 2003 presidential address to the American Economic Association" [@krugman].]. Obviously, they did not. Now, suppose my argument up to this point is completely wrong and there is, in fact, an exact core in economic science. Then we have that the paradigm's theory does not represent it, since, as Krugman points out, it has not been useful for making predictions. Naturally, I do not limit my critique to an instrumentalist position: the paradigm's theory also fails to explain social phenomena. Take growth theory, for example. For decades, models were developed—we have Solow's seminal formulation in 1956, still univariate; dynamic optimization with Ramsey-Cass-Koopmans in the 1960s; the attempt to explain it through human capital with Lucas in the 1980s; externalities and then technological innovation with Romer. Despite all the elegance and notation worthy of exact science academic theses, none of these works were able to explain the most basic questions about economic growth, notably the problems known as *catching up*, *falling behind*, and *forging ahead*. Therefore, the paradigm fails both from an instrumentalist and a conventionalist perspective.

I believe Krugman's critique is very pertinent and answers the initial question well: if economics is a social science, it cannot be investigated from a supposed objective reality, nor deduced from initial conditions and universal laws. In this sense, @herscovici highlights the limits of Popperian epistemology in economic analysis:

>In most cases, *to make a law universal, it is necessary to empty it of its historical content*. The *formalism* that results from this operation is characterized by the fact that, if a scientific law wants to explain all possible systems, it is unable to explain any real system, in its historical and social specificities.

These criticisms are not foreign to the authors. Still in the introduction of the work, they try to shield themselves:

>It seems naive to imagine that the economic agent is always a subject endowed with full rationality, perfect information, who acts in complete markets (with contingent commodities offered for all possible states of nature), who has clarity of their objectives and who always seeks the best result for themselves in the short term, without worrying about the remote consequences of their choices and without caring about others. Indeed, the economic paradigm has been criticized for the naivety of its behavioral assumptions in its analysis. But, in many cases, the label of naivety better characterizes the situation of those who make this type of criticism than the models of theoretical economists themselves, because the hypotheses listed above, in truth, are just simplifications from introductory textbooks. The frontier of theoretical knowledge in economics has long learned to deal with much bolder and more realistic behavioral hypotheses than these. Thus, current theoretical economists know perfectly well how to model agents with limited rationality, imperfect information, incomplete markets, undecided agents with multiple objectives, and who take into account the well-being of other people.

Well, one moment they say that a few institutions are enough for economists, among them the optimizing agent; another moment they say that such an agent has already been overcome. Worse, stating that "current theoretical economists know how to \textbf{perfectly model}" indecision seems doubly incoherent to me. First, because, by definition, there is no such thing as a "perfect model." Second, indecision, uncertainty, is stochastic by hypothesis. If one *assumes* uncertainty, one does not *perfectly model it*. But they go further:

>One can also criticize the assumptions of the economic paradigm for considering only the model of perfect competition. Another irrelevant criticism, because, varied (sic) market structures, from perfect competition to monopoly, began to be studied as early as the 19th century, and from the late 1920s theoretical knowledge deepened with the consideration of intermediate structures such as monopolistic competition and oligopoly. The assumptions of perfect competition were questioned and rethought by the influence of the criticism of economists of the so-called Austrian school of economics, but not only by it, and replaced by the view of the economic agent with active behavior in market exploration and discovery of opportunities. The basic model of monopoly was questioned and re-examined, in a dynamic context of the economy, by the renowned Joseph Schumpeter.

Ignoring that Schumpeter was a critic of the paradigm's methodological individualism, I draw attention to the issue of falsifiability in the field of exact sciences. The authors, while proposing a positivist view of economic science, invalidate it scientifically within Popperian philosophy itself by shielding the paradigm from the principle of falsifiability. According to the authors, one cannot question the adoption of the competitive hypothesis, despite it still being found in manuals and academic production; The problematic known as the Cambridge Controversy which, among other things, criticizes the use of production functions is also unfounded because economics today works with other mathematics --- but all microeconomics manuals, from undergraduate to postgraduate, are built on Lagrangian optimization in production functions. How can the law be timeless and change so much? How can it be universal and be only at the frontier of knowledge? Was perfect competition a universal law before and now it is not? Will today's frontier of knowledge be a universal law or will it have the same fate as the previous ones? By changing the demarcation of hypotheses to defend the theory, the paradigm becomes non-falsifiable and, therefore, ceases to be a scientific theory and becomes dogma.

Very clearly and somewhat contradictorily, the authors place the core of the maximizing equilibrium paradigm, the target of criticism from other schools of thought, as an incontestable truth:

>Traditional methodologists are greatly concerned with the empirical confrontation of theory and that the real world can effectively function as the ultimate judge in the validation and eventual discrediting of economic theories. The economic paradigm adheres to a method that indeed gives great importance to empirical evaluation. However, in this regard, two important observations are due: (1) not everything produced by the paradigm should be empirically tested; (2) not all theories are created to be tested. The economic paradigm can, therefore, be conceived as formed by a core containing only contributions of pure mathematics and a peripheral belt of theories that produce empirically testable conclusions.

Not being a subtle contradiction, they try to evade them shortly after, confusing, once again, economics—as a phenomenon that cannot be dissociated from its social specificities—with pure mathematical abstraction:

>Radical Popperian methodologists would revolt at the idea of economic theories that never confront empirical evidence. But, in fact, in the mathematical core of the economic paradigm, mathematical economists (or economic mathematicians) work as if they were in the environment of the pure mathematician. No methodologist, however extreme, would consider mathematics innocuous for not confronting empirical facts. Pure mathematical economics should also not be required to build some bridge connecting abstract models with some procedure of verification in observed facts.

The authors frequently compare the economic paradigm with the quantum-relativistic paradigm of modern physics. However, a superficial examination is enough to note the differences: has what is given as theory been abandoned? On the contrary, the body of knowledge is widely known and studied. It is not hidden only "at the frontier of knowledge," as the authors claim the elements that absolve economic theory from criticism are. The results found by Einstein at the beginning of the 20th century are still used to find bodies in the cosmos, from planets to black holes, and with each experiment they are put to the test and remain capable of explanation and prediction. Falsifiability does not work with absolute truths. Scientific knowledge is momentary and not permanent. A theory can only be qualified as scientific and significant as long as it can be tested and disproven.

But the authors do not allow its contestation, and the entrenchment continues with *ad hominem* arguments: if an economist is critical of economics as an exact science, then they do not understand mathematics:

>Let's look at the problem of misunderstanding mathematics. Critics of the use of mathematics in economics, in general, are not mathematical economists. Many of them did not have professional training in mathematics. They ventured into other areas. This does not mean they were not good students of mathematics. Marshall, for example, a critic of mathematics in economics, whose use, for him, should not be abusive, proved to be, before concentrating on economics, an excellent mathematician. Even Carl Menger, the father of the Austrian school, totally critical of the use of mathematics in economics, reportedly, was a good student of mathematics in high school. Keynes was a critic of mathematics, yet, a good mathematician, even without having the mind and experience of a professional mathematician. In fact, he graduated, with distinction, in this discipline.

Which is obviously an absurd argument. Imagine criticizing Foucault by saying: "critics of the police state, in general, are not police officers. Many of them did not have professional training in militarism." And they continue invalidating criticisms of the paradigm:

>The contrary view to mathematics of these classic exponents of scientific economics is perfectly understandable. Especially because they were bound by the mathematical development of their time. The problem is when, nowadays, the members of the schools bequeathed by them cling to the same criticisms of the use of mathematics, sustaining them in a crude and outdated view of mathematics. They criticize, for example, that economic variables do not obey functional relationships. But who said that current mathematical economics uses functions? Economists of the paradigm often work with correspondences, maps, and other mathematical techniques much more powerful than functions. They criticize the use of mathematics in economics based on the argument that economic variables do not describe a well-behaved trajectory; so that they cannot be accompanied by continuous and smooth curves, i.e., differentiable at all points. Who said that the current paradigm has to launch the hypothesis of differentiability and that it only uses differential and integral calculus? In fact, current economists of the paradigm work with convex analysis, which dispenses with the differentiability of functions, taking only the much weaker hypothesis of convexity. The existence of continuous curves is no longer imposed. They work with much more general and flexible descriptions, such as upper semicontinuity, etc. The use of calculus in mathematical economics has long been replaced by convex analysis, topology, and differential topology.

Well then, let's take the preface of an advanced mathematical economics work:

>In recent years, the usual optimisation techniques, which have proved so useful in microeconomic theory, have been extended to incorporate more powerful topological and differential methods, and these methods have led to new insights into the qualitative behaviour of general economic systems. These developments have necessarily resulted in an increase in the degree of formalism in the publications in the academic economic theory journals; a formalism which can often deter graduate students. My hope is that the progression of ideas presented here will familiarise the student with the geometric concepts underlying these topological methods, and, as a result, make modern mathematical economics and **general equilibrium theory** more accessible. [@schofield]

It is not a question of mathematical limitation or an absurd hierarchy of mathematics—as if topology were *better* than calculus, or something of the sort—but a question of propositions. It does not matter whether the theory studies consumer and firm optimization or Walrasian general equilibrium through topology or calculus, but it is the equilibrium itself, the maximizing behavior itself that is under criticism, and not the mathematics used to demonstrate it.

# THE PROGRAMMED ECONOMIST

So, why do theorists of the economic science paradigm continue to cling to such problematic concepts? In *Sistemas de Ensino e Sistemas de Pensamento*, Pierre Bourdieu posits the educational system as one of the most effective instruments for the moral and logical integration of society, which produces the "programmed" individual—homogeneous in perception, thought, and action:

>If one admits that culture and, in this particular case, erudite culture in its quality as a common code is what allows all holders of this code to associate the same meaning with the same works and, reciprocally, to express the same significant intention through the same words, the same behaviors, and the same works, one can understand why \textbf{the School, entrusted with transmitting this culture, constitutes the fundamental factor of cultural consensus} in terms of participation in a common sense understood as a condition for communication. [@bourdieu]

Perhaps, a similar logic has taken over scientific production. Apparently oblivious to the problem, the authors seem to celebrate homogeneous thought in economic science:

>Without explaining it for now, it is sufficient to say that the Kuhnian paradigm of economics is what undergraduate students are obliged to learn in theoretical disciplines. Every macroeconomics student studies textbooks written by authors such as Blanchard, Boyes, Dornbusch, [...]. Then it is observed, in Brazil and in the "free world," that students are subjected to the same training, because, despite differences in approach, style, and depth, all these didactic manuals of economic theory resemble each other in many aspects. In all of them, the institutions of private property, contract, maximizing agent, etc., thrive as presuppositions of theoretical models. All address economic problems with algebra and graphs, and develop equilibrium models. This homogeneous training of students is characteristic of the scientific practice that Kuhn calls normal science. Typical in sciences with consolidated paradigms. The economic paradigm subjects students to the same basic theoretical training. It is clear that similar training leads professionals trained in this environment to act in a standardized way in their work with their theories and in their empirical testing. [@feijo]

If we take poetic license to extend Bourdieu's theory of fields to the scientific community, we can imagine academic production located in the subfield of erudite production and the editors of *journals* in the field of power. In order to obtain greater symbolic capital, producers must publish in the most prestigious periodicals. Consequently, production submits to the standardized thought desired by the field of power. Now, the data that allow us to reason in this way are provided by the authors themselves:

>[...] in one of the most prestigious economics journals (if not the most prestigious in the world), more than half (54%) of the articles were about mathematical models without any data, almost a quarter of them (24.6%) were about empirical analysis, using statistical inference on published data or based on simulation and artificial experiments. Only 21.4% of the articles in the *American Economic Review* were dedicated to other topics, of which only 11.6% concerned models without mathematics and without data. Consider the 31 most prestigious international economics journals, which received an A1 classification from CAPES, among the international tops. Twenty of them focus heavily on articles with mathematical theories and eventual econometric tests; five are dedicated to publishing essays in applied economics and two are focused on econometrics (*Journal of Applied Econometrics, Journal of Econometrics*). Three others are distributed among history of economic thought (*History of Political Economy*), studies in methodology of economics (*Journal of Economic Methodology*), and reviews (*Journal of Economic Literature*). Only a single A1 journal publishes topics from economic schools not inserted in the paradigm (*Journal of Post Keynesian Economics*). So, of the 31 economics journals classified as A1, there is only one dedicated to a school of economic thought outside the paradigm of economic science, which prioritizes works in the line of so-called post-Keynesianism. It is also considered that studies outside this paradigm, including also Marxian, Austrian, institutional economics, etc., can be accepted for publication in at least three more A1 journals: *Cambridge Journal of Economics, Journal of Economic Methodology, and History of Political Economy*.

All this points to Bourdieu's thesis that "molded minds are predisposed to maintain with their peers a relationship of complicity and immediate communication." It is the common way of approaching common problems. They close themselves off in their common symbols, signs, language, and thought; they close themselves off to approaches and criticisms from those who do not use their common repertoire. And it is through this mechanism that economists continue to be caught off guard by crises that insist on finding them unprepared.
