---
title: O Papel Da Educação Matemática Sob A Hegemonia Do Capital
subtutle: Educação pré-capitalista
date: '2022-08-14'
categories: [education]
bibliography: bib.bib
---

::: {.callout-note}
Esse post foi tirado de um capítulo de minha [monografia de graduação em Matemática](https://repositorio.ifes.edu.br/handle/123456789/6060), defendida em 2024.
:::

Em uma sociedade capitalista, não se pode compreender a educação desassociada das relações de trabalho. Pois além das técnicas aplicadas à educação -- aí compreendidas a pedagogia em suas dimensões filosófica e sociológica --, as normas vigentes e valores compartilhados de uma determinada sociedade também são refletidas e moldam as ações educacionais.

Neste capítulo, procuro sistematizar os mecanismos de reprodução do capitalismo na educação, mostrando evidenciar como a educação matemática, enquanto não rompe com seu papel na reprodução das relações sociais de poder, é ineficaz na promoção de mudanças estruturais na sociedade.

Considere o seguinte exercício mental: Suponha uma sociedade em um futuro muito distante onde não exista trabalho como relação social. Robôs realizam toda a atividade laboral. Como seria a escola nessa sociedade? O que sobra de *puro* na educação? Qual seria seu propósito? Antes de tentar inferir qualquer coisa acerca de tais perguntas, podemos nos munir de uma breve visão geral do propósito da educação na história da educação.

De acordo com @cubberley_history_1920, na Atenas do século V a.C., antes do tempo dos sofistas, o currículo básico consistia de leitura, escrita, música e ginástica, e era requerido para a obtenção do *status* de cidadão. Somente detentores desse grau eram autorizados a participar das *ekklesia*, a principal assembléia da democracia ateniense. A educação, a qual era exclusiva para homens, era privada e as taxas dependiam da capacidade de pagamento dos pais. Apenas professores de grandes escolas tinham algum prestígio, com os demais ocupando posições baixas na hierarquia social ateniense. Gramática, aritimética, ciências ou línguas estrangeiras não faziam parte do currículo -- mas apenas aquilo que era necessário para a *normalização moral* do indivíduo ateniense: Música, literatura, sua própria religião, treinamento físico e instruções acerca das tarefas e obrigações de um cidadão.

Segundo o autor, as fábulas de Homero recheadas de heroismo, Ilíada e Odisséia, eram as primeiras e maiores leituras dos gregos, de forma que "_To appeal to the emotions and to stir the will along moral and civic lines was a fundamental purpose of the instruction_". Nessas obras, estavam incluídas lições de ética, política, vida social e, é claro, o que se espera de um soldado. Todos os elementos desejáveis para integração moral do futuro cidadão: severo mas simples e honesto, trabalhador, obediente às leis, que renega o conforto e o vício. O próprio retrato de Perseus refletido em cada menino grego.

Atravessando o Mar Jônico até Roma, suas primeiras escolas, cerca de 300 a.C., eram mais restritas que as atenienses, e tinham o propósito de intruir os jovens para a carreira política, sendo compostas por uma pequena e seleta parcela que tinha acesso à educação. Com a ascensão do império e a queda da grécia no século 2 a.C., o grande fluxo de gregos escolarizados para Roma causou o processo de helenização da cidade, de forma que as escolas romanas eram, de fato, escolas gregas ligeiramente modificadas para se adaptar a Roma. Em adição a gramática, composição, ética, história, mitologia e geografia, as escolas de retórica foram desenvolvidas para preparar os profissionais da lei e da vida pública em Roma. Homero continuava a ser o autor favorito em grego, mas agora as escolas contavam também com autores latino-romanos, como Virgílio e Horácio. Nas ciências, um pouco de geometria e astronomia foram adicionadas por sua utilidade prática. Com isso, as sete artes liberais da idade média -- gramática, retórica, dialética, aritmética, geometria, música e astronomia -- já estavam presentes [@cubberley_history_1920].

Assim como na sociedade ateniense, a educação era privada e reservada àqueles que pudessem pagar por 
ela. Os professores eram, ou pagãos, ou indiferentes a religião; e, por conta disso, as escolas eram cada vez menos frequentadas pelos cristãos, que cresciam rapidamente na população do império. Ao século V, as escolas romanas entraram em declínio, desaparecendo no século seguinte [@williams_history_2016].

Segundo @williams_history_2016, a intensa instabilidade da europa após a queda de Roma, somada à disseminação do cristianismo, tiveram grande impacto na educação, caracterizando o período da alta idade média como de densa ignorância, não apenas entre a população geral, mas também entre os nobres e apenas "levemente mitigada" entre a maior parte do clero. Ele lista como causas para a prevalência da ignorância: 1) a rejeição dos primeiros cristãos em relação a seus opressores pagãos, aí incluindo sua literatura, por conta não apenas de sua origem, como também pela mitologia que carrega; 2) Fora a bíblia, os livros eram caros e raros em relação ao império, uma vez que eles eram manuscritos e copiados à mão por escravos; 3) Esses poucos e caros livros eram escritos em latim, sendo ininteligíveis para a vasta maioria da população, uma vez que os diversos dialetos que eclodiram na região a partir das invasões bárbaras não eram desenvolvidos ou predominantes o suficiente durante a alta idade média; 4) A própria ideia e tradição de educação formal foi perdida culturalmente, perdendo seu valor como algo necessário; 5) Por fim, a partir do século IX, com a expansão do sistema feudal, o isolamento e os perigos associados às viagens durante o período potencializaram o custo de se obter educação e realizar as interações sociais necessárias para o desenvolvimento intelectual.

A educação formal no início da igreja cristã era apenas catecumenal, e sua principal preocuparação era a _regeneração moral da sociedade através da regeneração moral dos convertidos_ [@williams_history_2016]. Além disso, o esforço educacional da igreja estava fechada nela mesma, com o objetivo de criar sua base teológica, e não voltada para formação intelectual da sociedade a qual servia:

>Almost everything that we today mean by civilization in that age was found within the protecting walls of monastery or church, and these institutions were at first too busy building up the foundations upon which a future culture might rest to spend much time in preserving learning, much less in advancing it @[cubberley_history_1920].

Contrariamente às escolas clássicas, a educação cristã primitiva não possuía vocação intelectual, mas seu apelo era moral e emocional. De fato, os modelos grego e romano eram inteiramente rejeitados -- afinal, a educação intelectual pagã era a única disponível e os pais não desejavam que seus filhos tivessem contato e acabassem admirando as deidades do Olímpo. É apenas em meados do século II, com a fundação da escola catequética de Alexandria, que os membros do clero começam a receber treinamento a partir da educação e filosofia grega, formalizando sistematicamente a fé e doutrina cristã, que passa a receber cada vez mais influência do pensamento e filosofia grega. Entretanto, tal movimento seria revertido gradativamente até o início do século V, quando o concílio de Cartago, sob influência de Santo Agostinho, proíbe definitivamente a leitura de autores pagãos pelo clero [@cubberley_history_1920].

No século VI, a partir da fundação do monastério de Montecassino por São Benedito em 529 e a promulgação da regra Beneditina no ano 529, os monastérios se tornam os centros de educação, abertos não apenas para os meninos dispostos a assumir seus votos, como também, posteriormente (séc. IX), para alunos externos sem intenção de tomar votos. As escolas monásticas ofereciam instrução em leitura e escrita (em latim), música, _doutrina cristã e regras de conduta_. A cópia de manuscritos e preservação de livros antigos era uma das principais atividades dos monges, e, dentre os cristãos, a preservação da literatura clássica foi em grande parte devido a seus esforços [@williams_history_2016].

Fora do mundo católico romano, a conservação da literatura clássica na Europa em parte se deu por conta dos esforços da Espanha sarracena, no oeste, e dos bizantinos, no leste. Dentre os maometanos -- aqui expandindo a visão para califados como Bagdá, Bucara e Damasco --, a educação iniciava pela alfabetização e estudo do Quran, _com professores custeados pelo califado_. Para as famílias ricas, a educação continuava com o ensino de lógica, filosofia, teologia, astronomia e medicina. Diferente dos povos europeus da alta idade média, dependentes do latim, os sarracenos contavam com traduções em sírio da ciência grega e da filosofia aristotélica, aí incluindo a matemática de Euclides e a álgebra de Diophantus. Eles também foram responsáveis pela criação da química como ciência, além de grandes avanços na álgebra [@williams_history_2016].

Nos séculos seguintes, ao longo da Baixa Idade Média, o sistema educacional medieval desenvolvido pela igreja se torna mais organizado, fundamentados no _Trivium_ e _Quadrivium_. Entretanto, a educação continuava voltada para dentro da igreja, com a teologia como a única profissão e carreira a ser obtida através dela.

>All these schools, too, were completely under the control of the Church. There were no private schools or teachers before about 1200. Only the chivalric education was under the control of princes or kings, and even this the Church kept under its supervision. The Church was still the State, to a large degree, and the Church, unlike Greece or Rome, took the education of the young upon itself as one of its most important functions. The schools taught what the Church approved, and the instruction was for religious and church ends @[cubberley_history_1920].

Nesse sentido, a educação cristã medieval era, em sua essência, um instrumento de reprodução e perpetuação da própria estrutura de poder da igreja. De manutenção da ordem e da hierarquia social, e não de formação intelectual e crítica dos indivíduos.

Em 1450, o movimento de resgatar a literatura clássica e a filosofia grega e romana, conhecido como Renascimento, começa a se espalhar pela Europa a partir da Itália, trazendo consigo a redescoberta da matemática grega e árabe, além de agregar o estudo das humanidades ao lado da educação moral e física. Esse período marca a ruptura com o pensamento e educação clériga, e lança as bases para a educação moderna. Entretanto, de forma e conteúdo, pouco se tem de diferente da educação clássica grega e romana. Com o apoio das classes dominantes, a ascenção das escolas secundárias e unviersidades renascentistas restauraram a educação do tempo de Cícero, que trazia uma educação aristocrática, em preparação para serviços na Igreja, no Estado e nos grandes negócios.

>History was introduced in these schools for the first time and as a new subject of study, though the history was the history of Greece and Rome and was drawn from the authors studied. Livy and Plutarch were the chief historical writers used. Nothing that happened after the fall of Rome was deemed as of importance. Much emphasis was placed on manners, morality, and reverence, with Livy and Plutarch again as the great guides to conduct. $[...]$ The result was an all-round physical, mental, and moral training, vastly superior to anything previously offered by the cathedral and other church schools @[cubberley_history_1920].

Há vários outros eventos na história que podem ser analisados sob a ótica do seu impacto na educação: a reforma protestante^[Calvino escreve para o Príncipe de Genebra, em 1541, que "as artes liberais e a boa educação são bons auxiliares no pleno conhecimento da Palavra".], que, dentre vários outros desdobramentos, gera um novo nível de tolerância religiosa ao conhecimento que acaba por abrir caminho para o surgimento do método científico moderno [@cubberley_history_1920]; o sucesso da contra-reforma e da educação jesuíta nos processos colonizadores, que "promoveram o **controle da fé e da moral** dos habitantes" [@rosario_educacao_2015]; o puritanismo na América do Norte, que estabelece as bases do sistema educacional americano. Entretanto, o propósito deste trabalho não é de forma alguma ser exaustivo, mas sim de argumentar um ponto.

Voltando à pergunta inicial: o que sobra de puro na educação ao se retirar as relações sociais de exploracão e poder? Este estudante, ao inciar a leitura para este capítulo, tinha como hipótese e espera encontrar evidências de que a educação pré-capitalista tinha em seu cerne a curiosidade e o espírito humano, com foco nas artes. Entretanto, a história nos mostra que o elemento em comum que aparecem em todas as sociedades é a normalização moral do indivíduo e de reprodução das relações sociais vigentes, através da transmissão de valores e normas sociais e da formação dos filhos das classes dominantes para ocupar determinados postos na sociedade.
