---
title: THE ROLE OF MATHEMATICS EDUCATION UNDER THE HEGEMONY OF CAPITAL
subtitle: Pre-capitalist Education
date: '2022-08-14'
categories: [education]
bibliography: bib.bib
---

::: {.callout-note}
This post was taken from a chapter of my [undergraduate thesis in Mathematics](https://repositorio.ifes.edu.br/handle/123456789/6060), defended in 2024.
:::

In a capitalist society, education cannot be understood apart from labor relations. In addition to the techniques applied to education—including pedagogy in its philosophical and sociological dimensions—the prevailing norms and shared values of a given society are also reflected in and shape educational actions.

In this chapter, I seek to systematize the mechanisms of capitalism's reproduction in education, highlighting how mathematics education, as long as it does not break with its role in reproducing social power relations, is ineffective in promoting structural changes in society.

Consider the following thought experiment: Suppose a society in a very distant future where work as a social relation no longer exists. Robots perform all labor activities. What would school look like in this society? What remains *pure* in education? What would its purpose be? Before trying to infer anything about such questions, we can equip ourselves with a brief overview of the purpose of education in the history of education.

According to @cubberley_history_1920, in Athens in the 5th century BC, before the time of the sophists, the basic curriculum consisted of reading, writing, music, and gymnastics, and was required to obtain the status of citizen. Only those holding this status were allowed to participate in the *ekklesia*, the main assembly of Athenian democracy. Education, which was exclusive to men, was private and fees depended on the parents' ability to pay. Only teachers from large schools had any prestige, with the rest occupying low positions in the Athenian social hierarchy. Grammar, arithmetic, sciences, or foreign languages were not part of the curriculum—only what was necessary for the *moral normalization* of the Athenian individual: music, literature, their own religion, physical training, and instructions about the tasks and obligations of a citizen.

According to the author, Homer's fables filled with heroism, the Iliad and the Odyssey, were the first and greatest readings of the Greeks, so that "_To appeal to the emotions and to stir the will along moral and civic lines was a fundamental purpose of the instruction_". These works included lessons in ethics, politics, social life, and, of course, what was expected of a soldier. All the desirable elements for the moral integration of the future citizen: severe but simple and honest, hardworking, obedient to the laws, who rejects comfort and vice. The very portrait of Perseus reflected in every Greek boy.

Crossing the Ionian Sea to Rome, its first schools, around 300 BC, were more restricted than those of Athens and aimed to instruct young people for political careers, being composed of a small and select portion who had access to education. With the rise of the empire and the fall of Greece in the 2nd century BC, the great influx of educated Greeks to Rome caused the process of Hellenization of the city, so that Roman schools were, in fact, Greek schools slightly modified to adapt to Rome. In addition to grammar, composition, ethics, history, mythology, and geography, schools of rhetoric were developed to prepare professionals for law and public life in Rome. Homer remained the favorite author in Greek, but now schools also included Latin-Roman authors such as Virgil and Horace. In the sciences, a bit of geometry and astronomy were added for their practical utility. Thus, the seven liberal arts of the Middle Ages—grammar, rhetoric, dialectic, arithmetic, geometry, music, and astronomy—were already present [@cubberley_history_1920].

As in Athenian society, education was private and reserved for those who could pay for it. Teachers were either pagans or indifferent to religion; and, because of this, schools were less and less attended by Christians, who were rapidly growing in the empire's population. By the 5th century, Roman schools went into decline, disappearing in the following century [@williams_history_2016].

According to @williams_history_2016, the intense instability of Europe after the fall of Rome, combined with the spread of Christianity, had a great impact on education, characterizing the early Middle Ages as a period of dense ignorance, not only among the general population but also among the nobility and only "slightly mitigated" among most of the clergy. He lists as causes for the prevalence of ignorance: 1) the rejection by the early Christians of their pagan oppressors, including their literature, not only because of its origin but also because of the mythology it carried; 2) Except for the Bible, books were expensive and rare compared to the empire, since they were handwritten and copied by slaves; 3) These few and expensive books were written in Latin, being unintelligible to the vast majority of the population, since the various dialects that emerged in the region after the barbarian invasions were not developed or predominant enough during the early Middle Ages; 4) The very idea and tradition of formal education was culturally lost, losing its value as something necessary; 5) Finally, from the 9th century onwards, with the expansion of the feudal system, isolation and the dangers associated with travel during the period increased the cost of obtaining education and carrying out the social interactions necessary for intellectual development.

Formal education at the beginning of the Christian church was only catechumenal, and its main concern was the _moral regeneration of society through the moral regeneration of converts_ [@williams_history_2016]. Furthermore, the church's educational effort was closed in on itself, with the aim of creating its theological base, and not aimed at the intellectual formation of the society it served:

>Almost everything that we today mean by civilization in that age was found within the protecting walls of monastery or church, and these institutions were at first too busy building up the foundations upon which a future culture might rest to spend much time in preserving learning, much less in advancing it @[cubberley_history_1920].

Contrary to classical schools, early Christian education had no intellectual vocation, but its appeal was moral and emotional. In fact, the Greek and Roman models were entirely rejected—after all, pagan intellectual education was the only one available and parents did not want their children to have contact with and end up admiring the deities of Olympus. It is only in the middle of the 2nd century, with the foundation of the catechetical school of Alexandria, that members of the clergy begin to receive training based on Greek education and philosophy, systematically formalizing the Christian faith and doctrine, which increasingly received influence from Greek thought and philosophy. However, such a movement would be gradually reversed until the beginning of the 5th century, when the Council of Carthage, under the influence of Saint Augustine, definitively prohibited the reading of pagan authors by the clergy [@cubberley_history_1920].

In the 6th century, with the foundation of the monastery of Monte Cassino by Saint Benedict in 529 and the promulgation of the Benedictine rule in 529, monasteries became centers of education, open not only to boys willing to take vows, but also, later (9th century), to external students with no intention of taking vows. Monastic schools offered instruction in reading and writing (in Latin), music, _Christian doctrine and rules of conduct_. The copying of manuscripts and preservation of ancient books was one of the main activities of the monks, and among Christians, the preservation of classical literature was largely due to their efforts [@williams_history_2016].

Outside the Roman Catholic world, the conservation of classical literature in Europe was partly due to the efforts of Saracen Spain in the west and the Byzantines in the east. Among the Mohammedans—here expanding the view to caliphates such as Baghdad, Bukhara, and Damascus—education began with literacy and study of the Quran, _with teachers funded by the caliphate_. For wealthy families, education continued with the teaching of logic, philosophy, theology, astronomy, and medicine. Unlike the European peoples of the early Middle Ages, dependent on Latin, the Saracens had Syriac translations of Greek science and Aristotelian philosophy, including Euclid's mathematics and Diophantus's algebra. They were also responsible for the creation of chemistry as a science, as well as great advances in algebra [@williams_history_2016].

In the following centuries, throughout the Late Middle Ages, the medieval educational system developed by the church became more organized, based on the _Trivium_ and _Quadrivium_. However, education continued to be directed inward to the church, with theology as the only profession and career to be obtained through it.

>All these schools, too, were completely under the control of the Church. There were no private schools or teachers before about 1200. Only the chivalric education was under the control of princes or kings, and even this the Church kept under its supervision. The Church was still the State, to a large degree, and the Church, unlike Greece or Rome, took the education of the young upon itself as one of its most important functions. The schools taught what the Church approved, and the instruction was for religious and church ends @[cubberley_history_1920].

In this sense, medieval Christian education was, in essence, an instrument for reproducing and perpetuating the church's own power structure. For maintaining order and social hierarchy, not for the intellectual and critical formation of individuals.

In 1450, the movement to rescue classical literature and Greek and Roman philosophy, known as the Renaissance, began to spread across Europe from Italy, bringing with it the rediscovery of Greek and Arab mathematics, as well as adding the study of the humanities alongside moral and physical education. This period marks the break with clerical thought and education and lays the foundations for modern education. However, in form and content, there is little difference from classical Greek and Roman education. With the support of the ruling classes, the rise of Renaissance secondary schools and universities restored the education of Cicero's time, which brought an aristocratic education, preparing for services in the Church, the State, and big business.

>History was introduced in these schools for the first time and as a new subject of study, though the history was the history of Greece and Rome and was drawn from the authors studied. Livy and Plutarch were the chief historical writers used. Nothing that happened after the fall of Rome was deemed as of importance. Much emphasis was placed on manners, morality, and reverence, with Livy and Plutarch again as the great guides to conduct. $[...]$ The result was an all-round physical, mental, and moral training, vastly superior to anything previously offered by the cathedral and other church schools @[cubberley_history_1920].

There are several other events in history that can be analyzed from the perspective of their impact on education: the Protestant Reformation^[Calvin writes to the Prince of Geneva, in 1541, that "the liberal arts and good education are good aids in the full knowledge of the Word".], which, among many other developments, generates a new level of religious tolerance for knowledge that eventually paves the way for the emergence of the modern scientific method [@cubberley_history_1920]; the success of the Counter-Reformation and Jesuit education in the colonization processes, which "promoted the **control of faith and morals** of the inhabitants" [@rosario_educacao_2015]; Puritanism in North America, which establishes the foundations of the American educational system. However, the purpose of this work is by no means to be exhaustive, but rather to argue a point.

Returning to the initial question: what remains pure in education when social relations of exploitation and power are removed? This student, when beginning the reading for this chapter, hypothesized and expected to find evidence that pre-capitalist education had at its core curiosity and the human spirit, with a focus on the arts. However, history shows us that the common element that appears in all societies is the moral normalization of the individual and the reproduction of prevailing social relations, through the transmission of values and social norms and the training of the children of the ruling classes to occupy certain positions in society.
