---
title: A Escola como Instituição Panóptica
author: Alberson Miranda
date: '2022-08-14'
slug: panoptismo-escola
categories:
  - Educação
tags:
  - Matemática
  - Educação
description: Uma leitura da escola como instituição panóptica de acordo com Foucault, com elementos de Bourdieu e uma crítica a Lins.
featured: yes
draft: no
toc: no
featureImage:
thumbnail:
shareImage:
codeMaxLines: 10
codeLineNumbers: yes
figurePositionShow: yes
bibliography:
  - ../bib.bib
bibEntry: datamares_
link-citations: yes
---

Em seu texto acerca dos Parâmetros Curriculares Nacionais --- PCN, o professor Rômulo Lins abre da seguinte forma:

> Provavelmente o maior problema da educação matemática dos brasileiros não esteja nas atuais deficiências apontadas diversas vezes, tais como, por exemplo, formação inadequada de professores e abordagens inadequadas sendo levadas para as salas de aula. Parece-me que o maior problema é a resistência do sistema em mudar. [@lins]

Para ele, a pesquisa relacionada às técnicas e abordagens em sala de aula, o que ele chamou de *micro*, não é suficiente para colocar o sistema educacional em rota de mudança. Paralelamente, deve ser realizado um trabalho estrutural na esfera *macro* --- aqui, principalmente, o MEC --- que possibilite uma mudança do educar *pela* matemática para o educar *para* a matemática. Essa diferença é ilustrada por Lins da seguinte forma:

>A diferença fica bastante mais clara se pensamos no caso da Educação Física. Será que alguém concebe que o papel das aulas de Educação Física é preparar todas as crianças (todas, eu disse) para o esporte competitivo? Claro que não. Se assim fosse as aulas de Educação Física não representariam, na formação das crianças, a educação para a saúde, para o desenvolvimento motor, para a socialização e o respeito a regras, para a colaboração. E os que quiserem ser atletas e jogadores vão buscar esta formação específica em outros espaços (possivelmente dentro dos times competitivos de suas escolas ou em clubes). Podemos dizer que a Educação Física escolar se concentra em modos de ser, promovendo aquela educação POR MEIO de esportes e exercícios físicos, enquanto o Treinamento Esportivo se concentra em potencializar habilidades, fazendo isso por meio da aquisição de técnicas específicas. [@lins]

A mudança, então, deixa de ter como meio apenas a sala de aula; o problema norteador da educação matemática como disciplina deixa de ser apenas, por exemplo, se o aluno deve ou não estudar geometrias não euclidianas no ensino médio, ou seja, unicamente conteúdos, e se expande para questionar o próprio objetivo do ensino da matemática, ou melhor, *através* da matemática.

Quando o autor propõe uma educação "formativa e com o objetivo de permitir que todos que passem por ela participem de forma plena em suas sociedades", podemos nos perguntar: o que é essa participação plena? Ou ainda, por que é tão difícil realizar mudanças estruturais na educação ou, como Lins diz, fazer com que o sistema se coloque em rota de mudança? Podemos analisar essas perguntas sob a ótica da Sociologia da Educação.

Em *Sistemas de Ensino e Sistemas de Pensamento*, Pierre Bourdieu coloca o sistema educacional como um dos instrumentos mais eficazes de integração moral e lógica da sociedade, que tem como produto o indivíduo "programado" — homogêneo em percepção, pensamento e ação:

>Caso se admita que a cultura e, neste caso particular, a cultura erudita em sua qualidade de código comum é o que permite a todos os detentores deste código associar o mesmo sentido às mesmas obras e, de maneira recíproca, de exprimir a mesma intenção significante por intermédio das mesmas palavras, dos mesmos comportamentos e das mesmas obras, pode-se compreender por que **a Escola, incumbida de transmitir esta cultura, constitui o fator fundamental do consenso cultural** nos termos de uma participação de um senso comum entendido como condição da comunicação. [@bourdieu]
\end{citacao}

Na conferência V de *A Verdade e as Formas Jurídicas*, Foucault coloca a escola como um exemplo de instituição panóptica (ou de sequestro). Esse tipo de instituição exerce poder sobre os indivíduos em uma sociedade de três formas características: *vigilância* individual e contínua; *controle* através de punição e recompensa e; formação e transformação dos indivíduos em função de certas normas, o que Foucault chamou de *correção*. Podemos associar esse consenso cultural que Bourdieu trata ao tríplice aspecto das instituições panópticas na definição de Foucault, especificamente a *correção*. 

>Na época atual, todas essas instituições --- fábrica, escola, hospital psiquiátrico, hospital, prisão --- têm por finalidade não excluir, mas, ao contrário, fixar os indivíduos. A fábrica não exclui os indivíduos; liga-os a um aparelho de produção. **A escola não exclui os indivíduos; mesmo fechando-os; ela os fixa a um aparelho de transmissão do saber**. O hospital psiquiátrico não exclui os indivíduos; liga-os a um aparelho de correção, a um aparelho de normalização dos indivíduos. O mesmo acontece com a casa de correção ou com a prisão. Mesmo se os efeitos dessas instituições são a exclusão do indivíduo, elas têm como finalidade primeira fixar os indivíduos em um aparelho de normalização dos homens. A fábrica, **a escola**, a prisão ou os hospitais **têm por objetivo ligar o indivíduo a um processo de produção, de formação ou de correção dos produtores. Trata-se de garantir a produção ou os produtores em função de uma determinada norma**. [@foucault, p. 114]

A primeira função da instituição panóptica é a extração da totalidade do tempo do indivíduo. É preciso que todo o tempo da existência humana esteja disponível ao trabalho, suas exigências ou sua preparação --- aí incluindo a educação, que os economistas chamam frequentemente de capital humano. Ao sequestrar o tempo do homem, ela transforma seu tempo de vida em tempo de trabalho. A segunda função é controlar seus corpos, fazendo com que o corpo do indivíduo se torne força de trabalho. Aqui o corpo humano deve ser formado, reformado, corrigido; deve "adquirir aptidões, receber um certo número de qualidades, qualificar-se como um corpo capaz de trabalhar". 

A terceira função é a criação de um micro-poder político, econômico e judiciário. A instituição panóptica se outorga o direito de decidir, comandar, punir, recompensar e julgar. E a escola não passa desapercebida:

> O sistema escolar também é inteiramente baseado em uma espécie de poder judiciário. A todo poder se pune e recompensa, se avalia, se classifica, se diz quem é o melhor, quem é o pior. [...] Por que, para ensinar alguma coisa a alguém, se deve punir e recompensar? Esse sistema parece evidente, mas, se refletirmos, vemos que a evidência se dissolve. [@foucault, p. 120]

Por fim, a quarta função é a extração do saber, tanto a partir da apropriação do conhecimento técnico e tecnológico produzido durante o labor, quanto da observação do comportamento dos indivíduos vigiados e controlados. Da mesma forma que as anteriores, essa função não é restrita às relações sociais do capitalismo moderno:

>A pedagogia se formou a partir das próprias adaptações da criança às tarefas escolares, adaptações observadas e extraídas do seu comportamento para tornarem-se em seguida leis de funcionamento das instituições e forma de poder exercido sobre a criança. [@foucault, p. 122]

Esse conjunto de características tem como objetivo principal a *transformação dos homens em força produtiva*. É através desse micro-poder entranhado nas relações sociais de uma sociedade panóptica que o indivíduo é fixado ao aparelho de produção, e a escola é um instrumento essencial para a formação desse micro-poder.

Tendemos, por conta da brevidade de nossas vidas, a limitar nossa ousadia em relação a essas estruturas. É fácil internalizar, inconscientemente, que essas instituições sempre existiram e sempre existirão da mesma forma que o são hoje. E talvez essa seja uma razão que contribua para que, como aponta Lins, a produção na educação matemática seja tão limitada à sala de aula --- aliás, essa visão é incentivada aqui mesmo no IFES, onde somos direcionados a "trazer para a sala de aula" nossa pesquisa do TCC.

Enquanto a educação exercer esse papel na sociedade, a sua estrutura é inalterada na essência. Portanto, além de pensar no que Lins define como micro e macro, devemos avançar acerca da própria posição da educação na sociedade. Apenas no momento em que a escola não mais existir para normalizar o indivíduo é que ela perderá sua razão de ser numa sociedade panóptica capitalista e será livre para se tornar algo diferente --- e de fato libertadora.

# CITATION

{{% citacao %}}

# REFERÊNCIAS