---
title: "Creating a Linux Personal Package Archive (PPA)"
subtitle: "How I created my own PPA to distribute RStudio, Quarto and Positron."
date: "2025-06-09"
categories: [tools]
---

```{r options, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  out.width = "100%",
  warnings = FALSE,
  message = FALSE
)

# packages

```

::: {.callout-tip}
## TL;DR

A new [PPA](https://github.com/albersonmiranda/r_tools_ppa) is now available for Ubuntu and Fedora users, simplifying the installation of the latest RStudio, Quarto, and Positron versions with a single command. I maintain this PPA and update it daily with the newest releases of these tools.

:::

As a millennial, I, like many, navigated the early internet by pirating software—from Windows XP to Adobe CS5, nothing was safe from my teenage rebellion. However, as I matured, I grew tired of proprietary software and decided to explore open-source alternatives. My journey began with Ubuntu, and soon after, I discovered Fedora, which I enjoyed even more. What particularly captivated me about Linux was the power of its package management system: the ability to install, update, and remove almost any software with a single command—and keep it updated! While this system is incredibly convenient, not all software is available in official repositories. This is where Personal Package Archives (PPAs) really shine. PPAs allow developers to distribute their software directly, providing access to newer versions or tools not found in the standard channels. In this post, I'm sharing my project which you can use to create your own PPA to distribute your software.

::: {.callout-tip}
## What is a PPA?

A Personal Package Archive (PPA) is a software repository that allows developers to distribute their software to Ubuntu users. That's a Debian based nomenclature, but the concept is similar in other Linux distributions and I'll call it PPA throughout this post.

:::

## Easy installation for RStudio, Quarto and Positron

Right now, there are no official repositories for Rstudio, Quarto or Positron for Linux. This means that users have to download the binaries from their respective websites and install them manually. But I wanted the same experience of macOS users, who can count on Positron software distribution via Homebrew. There are some unofficial PPAs available for Rstudio, but I couldn't find any for Quarto or Positron, So I've decided to make my own and share with you!

What [this project](https://github.com/albersonmiranda/r_tools_ppa) do is scraping the urls for the latest versions of Rstudio, Quarto and Positron from their respective websites or Github releases, download the files, upload them to [Sourceforge](https://sourceforge.net/projects/r-tools-ppa/files/) and finally create a PPA that can be used to install these tools on Ubuntu, Fedora and other Linux distributions.

[This two scripts](https://github.com/albersonmiranda/r_tools_ppa/tree/main/scripts) holds the logic to create the PPA:

1. Define the latest versions of RStudio, Quarto and Positron.
2. Download the binaries from their respective websites or Github releases.
3. Upload the binaries to Sourceforge.
4. Generate the metadata files required for the PPA.
5. Create the release files for the PPA.
6. Generate checksums for the files.s

## Support

- .deb packages for Ubuntu and Debian-based distributions.
  - Rstudio (amd64)
  - Quarto (amd64 and arm64)
  - Positron (amd64 and arm64)
- .rpm packages for Fedora and Red Hat-based distributions.
  - Rstudio (x86_64)
  - Positron (x86_64 and aarch64)
  - Quarto (x86_64)

## Debian/Ubuntu Installation

To enable this repository and install the latest RStudio, Quarto, or
Positron:

1.  Add the repository (amd64):

    ``` bash
    echo "deb [trusted=yes] https://downloads.sourceforge.net/project/r-tools-ppa/deb_amd64 stable main" | sudo tee /etc/apt/sources.list.d/r_tools_ppa.list
    sudo apt update
    ```

    Or for arm64:

    ``` bash
    echo "deb [trusted=yes] https://downloads.sourceforge.net/project/r-tools-ppa/deb_arm64 stable main" | sudo tee /etc/apt/sources.list.d/r_tools_ppa.list
    sudo apt update
    ```

2.  Install a package (e.g., RStudio):

    ``` bash
    sudo apt install rstudio
    ```

## Fedora/Red Hat Installation

To enable this repository and install the latest RStudio, Quarto, or
Positron:

1.  Download the repository file:

    ``` bash
    sudo curl -L -o /etc/yum.repos.d/r_tools_ppa.repo \
      https://sourceforge.net/projects/r-tools-ppa/files/rpm_x86_64/repo.txt/download
    ```

    Or for aarch64 architecture:

    ``` bash
    sudo curl -o /etc/yum.repos.d/r_tools_ppa.repo \
      https://sourceforge.net/projects/r-tools-ppa/files/rpm_aarch64/repo.txt/download
    ```

2.  Update & install (e.g., RStudio):

    ``` bash
    sudo dnf update
    sudo dnf install rstudio
    ```
