---
title: "Criando um Personal Package Archive (PPA) no Linux"
subtitle: "Como criei meu próprio PPA para distribuir RStudio, Quarto e Positron."
date: "2025-06-09"
categories: [ferramentas]
---

```{r options, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  out.width = "100%",
  warnings = FALSE,
  message = FALSE
)

# pacotes

```

::: {.callout-tip}
## TL;DR

Há um novo [PPA](https://github.com/albersonmiranda/r_tools_ppa) disponível para usuários de Ubuntu e Fedora que permite instalar as versões mais recentes do RStudio, Quarto e Positron com um único comando. Este PPA é mantido por mim e é atualizado diariamente com as versões mais recentes dessas ferramentas.

:::

Como um millennial, cresci pirateando coisas da internet. Do Windows XP ao Adobe CS5, nada estava a salvo da minha rebeldia adolescente. Com o tempo, cansei de softwares proprietários e decidi dar uma chance às alternativas de código aberto. Me apaixonei pelo Ubuntu e logo depois experimentei o Fedora, que gostei ainda mais! Uma das coisas que me conquistou foi o fato de poder instalar praticamente qualquer software com um único comando — e mantê-lo atualizado! Isso é possível graças ao sistema de gerenciamento de pacotes do Linux, que permite instalar, atualizar e remover softwares facilmente. Mas nem todo software está disponível nos repositórios oficiais, e é aí que os Personal Package Archives (PPAs) são úteis. PPAs são uma forma de desenvolvedores distribuírem seus softwares para usuários do Ubuntu, podendo ser usados para instalar programas que não estão nos repositórios oficiais ou obter a versão mais recente de um pacote. Neste post, vou mostrar como criar seu próprio PPA e como usá-lo para distribuir seu software.

::: {.callout-tip}
## O que é um PPA?

Um Personal Package Archive (PPA) é um repositório de software que permite aos desenvolvedores distribuir seus programas para usuários do Ubuntu. Esse é um termo do mundo Debian, mas o conceito é semelhante em outras distribuições Linux e vou chamá-lo de PPA ao longo deste post.

:::

## Instalação fácil para RStudio, Quarto e Positron

Atualmente, não há repositórios oficiais para RStudio, Quarto ou Positron no Linux. Isso significa que os usuários precisam baixar os binários dos sites oficiais e instalar manualmente. Mas eu queria a mesma experiência dos usuários de macOS, que contam com a distribuição dos softwares da Positron via Homebrew. Existem alguns PPAs não oficiais para o RStudio, mas não encontrei nenhum para o Quarto ou Positron. Então decidi criar o meu próprio e compartilhar com vocês!

O que [este projeto](https://github.com/albersonmiranda/r_tools_ppa) faz é buscar as URLs das versões mais recentes do RStudio, Quarto e Positron em seus respectivos sites ou releases do Github, baixar os arquivos, enviá-los para o [Sourceforge](https://sourceforge.net/projects/r-tools-ppa/files/) e finalmente criar um PPA que pode ser usado para instalar essas ferramentas no Ubuntu, Fedora e outras distribuições Linux.

## Suporte

- Pacotes .deb para distribuições baseadas em Ubuntu e Debian.
  - RStudio (amd64)
  - Quarto (amd64 e arm64)
  - Positron (amd64 e arm64)
- Pacotes .rpm para distribuições baseadas em Fedora e Red Hat.
  - RStudio (x86_64)
  - Positron (x86_64 e aarch64)
  - Quarto (x86_64)

## Instalação no Debian/Ubuntu

Para habilitar este repositório e instalar a versão mais recente do RStudio, Quarto ou Positron:

1.  Adicione o repositório (amd64):

    ``` bash
    echo "deb [trusted=yes] https://downloads.sourceforge.net/project/r-tools-ppa/deb_amd64 stable main" | sudo tee /etc/apt/sources.list.d/r_tools_ppa.list
    sudo apt update
    ```

    Ou para arm64:

    ``` bash
    echo "deb [trusted=yes] https://downloads.sourceforge.net/project/r-tools-ppa/deb_arm64 stable main" | sudo tee /etc/apt/sources.list.d/r_tools_ppa.list
    sudo apt update
    ```

2.  Instale um pacote (ex: RStudio):

    ``` bash
    sudo apt install rstudio
    ```

## Instalação no Fedora/Red Hat

Para habilitar este repositório e instalar a versão mais recente do RStudio, Quarto ou Positron:

1.  Baixe o arquivo do repositório:

    ``` bash
    sudo curl -L -o /etc/yum.repos.d/r_tools_ppa.repo \
      https://sourceforge.net/projects/r-tools-ppa/files/rpm_x86_64/repo.txt/download
    ```

    Ou para arquitetura aarch64:

    ``` bash
    sudo curl -o /etc/yum.repos.d/r_tools_ppa.repo \
      https://sourceforge.net/projects/r-tools-ppa/files/rpm_aarch64/repo.txt/download
    ```

2.  Atualize e instale (ex: RStudio):

    ``` bash
    sudo dnf update
    sudo dnf install rstudio
    ```
