on:
  push:
    branches: [main, master]

name: Build & Deploy

permissions:
  contents: write

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-renv@v
      - name: Render
        run: Rscript -e 'babelquarto::render_website()'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Commit blog"