on:
  workflow_dispatch:
  push:
    branches: master

name: Publish to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R package deps
        run: sudo apt install libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev libxslt1-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.3"

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render
        run: Rscript -e 'babelquarto::render_website()'

      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true